version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn package -DskipTests
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: ~/junit
  trigger-depndents:
    machine: true
      steps:
      - run:
          name: Clone docs
          working_directory: ~/workdir
          command: |
            git clone --depth 1 https://github.com/assadriaz/demo.git
      - deploy:
          name: Trigger demo deployment
          working_directory: ~/workdir/demo
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "<email>"
            git config user.name "CricleCI Bot"
            git commit --allow-empty -m "CricleCI: Updated dependency SpringBootReact "
            # Push quietly to prevent showing the token in log
            git push -q https://${DEMO_GITHUB_TOKEN}@github.com/assadriaz/demo.git master

workflows:
  version: 2
  build_test_deploy:
    jobs:
    - build:
        context: demo
        filters:
          branches:
            only: master
    - trigger-dependants:
        contex: demo
        requires:
          - build