version: 2
aliases:
- &post-hook
  name: Notify about build and docker image pushed
  command: |
    echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
    echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
    echo 'export BUILD_STATUS_API_KEY="$BUILD_STATUS_API_KEY"' >> $BASH_ENV
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn package
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: ~/junit
    - run: *post-hook

workflows:
  version: 2
  build_test_deploy:
    jobs:
    - build:
        context: org-carbon
    - deploy-docker:
        context: org-carbon
        requires:
        - build
        filters:
          branches:
            only: master